### ISSUE TITLE
How to leave a comment

### ISSUE THREAD

**Issue by bender2k14** [parsonsmatt/parsonsmatt.github.io#17]
Hello.  Is it possible to leave a comment on one of your blog posts?  I tried to find an example to copy, but I  came up empty handed.

**Comment by parsonsmatt** [comment]
You can leave a "comment" on GitHub as an issue, or make a PR to a blog post with edit/suggestions. 

I usually post discussions to Reddit's `/r/haskell` community, and other folks sometimes post to other discussion websites. Since this is a statically rendered site, I'd need to shell out to Disqus or similar for hosting comments, and I don't want to do that. I'd rather discussion happen on websites that are centered on that, like Twitter, Reddit, Lobsters, etc.

**Comment by bender2k14** [comment]
Sounds good.  I don't use any of those social media or discussion sites, so I will create an issue to make my comment.

As an alternative, you can allow for comment like Mark Seemann does on his blog.  Here is an example.
https://github.com/ploeh/ploeh.github.com/pull/411
